// Generated by Haxe 3.4.2
package com.example.app;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Controller extends haxe.lang.HxObject
{
	public Controller(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Controller()
	{
		//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
		com.example.app.Controller.__hx_ctor_com_example_app_Controller(this);
	}
	
	
	public static void __hx_ctor_com_example_app_Controller(com.example.app.Controller __hx_this)
	{
	}
	
	
	public com.example.app.AppContext context;
	
	public void onEnter()
	{
	}
	
	
	public void onLeave()
	{
	}
	
	
	public void setPage(com.example.app.Page page)
	{
		//line 27 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
		this.context.setView(page.render());
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
		{
			//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
			boolean __temp_executeDef1 = true;
			//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
			switch (field.hashCode())
			{
				case 951530927:
				{
					//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
					if (field.equals("context")) 
					{
						//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
						__temp_executeDef1 = false;
						//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
						this.context = ((com.example.app.AppContext) (value) );
						//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
						return value;
					}
					
					//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
					break;
				}
				
				
			}
			
			//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
			if (__temp_executeDef1) 
			{
				//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
		{
			//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
			boolean __temp_executeDef1 = true;
			//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
			switch (field.hashCode())
			{
				case 1984860689:
				{
					//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
					if (field.equals("setPage")) 
					{
						//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
						__temp_executeDef1 = false;
						//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "setPage")) );
					}
					
					//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
					break;
				}
				
				
				case 951530927:
				{
					//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
					if (field.equals("context")) 
					{
						//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
						__temp_executeDef1 = false;
						//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
						return this.context;
					}
					
					//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
					break;
				}
				
				
				case -1343806440:
				{
					//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
					if (field.equals("onLeave")) 
					{
						//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
						__temp_executeDef1 = false;
						//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "onLeave")) );
					}
					
					//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
					break;
				}
				
				
				case -1349985223:
				{
					//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
					if (field.equals("onEnter")) 
					{
						//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
						__temp_executeDef1 = false;
						//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "onEnter")) );
					}
					
					//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
					break;
				}
				
				
			}
			
			//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
			if (__temp_executeDef1) 
			{
				//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
		{
			//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
			boolean __temp_executeDef1 = true;
			//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
			switch (field.hashCode())
			{
				case 1984860689:
				{
					//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
					if (field.equals("setPage")) 
					{
						//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
						__temp_executeDef1 = false;
						//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
						this.setPage(((com.example.app.Page) (dynargs.__get(0)) ));
					}
					
					//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
					break;
				}
				
				
				case -1349985223:
				{
					//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
					if (field.equals("onEnter")) 
					{
						//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
						__temp_executeDef1 = false;
						//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
						this.onEnter();
					}
					
					//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
					break;
				}
				
				
				case -1343806440:
				{
					//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
					if (field.equals("onLeave")) 
					{
						//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
						__temp_executeDef1 = false;
						//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
						this.onLeave();
					}
					
					//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
					break;
				}
				
				
			}
			
			//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
			if (__temp_executeDef1) 
			{
				//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
		baseArr.push("context");
		//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


