// Generated by Haxe 3.4.2
package com.example.app;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public interface IApplication extends haxe.lang.IHxObject
{
	void onReady(com.example.app.AppContext context);
	
}


