// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
package com.example.app;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class ListModel<T> extends haxe.lang.HxObject
{
	public ListModel(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public ListModel(haxe.root.Array<T> array)
	{
		//line 12 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
		com.example.app.ListModel.__hx_ctor_com_example_app_ListModel(((com.example.app.ListModel<T>) (this) ), ((haxe.root.Array<T>) (array) ));
	}
	
	
	public static <T_c> void __hx_ctor_com_example_app_ListModel(com.example.app.ListModel<T_c> __hx_this, haxe.root.Array<T_c> array)
	{
		//line 13 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
		__hx_this.items = ( (( array != null )) ? (array) : (new haxe.root.Array<T_c>()) );
	}
	
	
	public haxe.root.Array<T> items;
	
	
	
	public int get_length()
	{
		//line 9 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
		return this.items.length;
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
		{
			//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
			switch (field.hashCode())
			{
				case 100526016:
				{
					//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
					if (field.equals("items")) 
					{
						//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
						__temp_executeDef1 = false;
						//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
						this.items = ((haxe.root.Array<T>) (value) );
						//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
						return value;
					}
					
					//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
					break;
				}
				
				
			}
			
			//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
		{
			//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
			switch (field.hashCode())
			{
				case 974314479:
				{
					//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
					if (field.equals("get_length")) 
					{
						//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
						__temp_executeDef1 = false;
						//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_length")) );
					}
					
					//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
					break;
				}
				
				
				case 100526016:
				{
					//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
					if (field.equals("items")) 
					{
						//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
						__temp_executeDef1 = false;
						//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
						return this.items;
					}
					
					//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
					break;
				}
				
				
				case -1106363674:
				{
					//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
					if (field.equals("length")) 
					{
						//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
						__temp_executeDef1 = false;
						//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
						return this.get_length();
					}
					
					//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
					break;
				}
				
				
			}
			
			//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
		{
			//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
			switch (field.hashCode())
			{
				case -1106363674:
				{
					//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
					if (field.equals("length")) 
					{
						//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
						__temp_executeDef1 = false;
						//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
						return ((double) (this.get_length()) );
					}
					
					//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
					break;
				}
				
				
			}
			
			//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
		{
			//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
			switch (field.hashCode())
			{
				case 974314479:
				{
					//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
					if (field.equals("get_length")) 
					{
						//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
						__temp_executeDef1 = false;
						//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
						return this.get_length();
					}
					
					//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
					break;
				}
				
				
			}
			
			//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			else
			{
				//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
		baseArr.push("length");
		//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
		baseArr.push("items");
		//line 3 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\ListModel.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


