// Generated by Haxe 3.4.2
package com.example.app;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Main extends haxe.lang.HxObject implements com.example.app.IApplication
{
	public Main(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Main()
	{
		//line 4 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
		com.example.app.Main.__hx_ctor_com_example_app_Main(this);
	}
	
	
	public static void __hx_ctor_com_example_app_Main(com.example.app.Main __hx_this)
	{
	}
	
	
	public void onReady(com.example.app.AppContext context)
	{
		//line 7 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
		context.registerController(com.example.app.MainController.class);
		//line 8 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
		context.registerController(com.example.app.SecondController.class);
		//line 10 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
		context.navigate(com.example.app.MainController.class);
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 4 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
		{
			//line 4 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
			boolean __temp_executeDef1 = true;
			//line 4 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
			switch (field.hashCode())
			{
				case -1338265852:
				{
					//line 4 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
					if (field.equals("onReady")) 
					{
						//line 4 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
						__temp_executeDef1 = false;
						//line 4 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "onReady")) );
					}
					
					//line 4 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
					break;
				}
				
				
			}
			
			//line 4 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
			if (__temp_executeDef1) 
			{
				//line 4 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 4 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		//line 4 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
		{
			//line 4 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
			boolean __temp_executeDef1 = true;
			//line 4 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
			switch (field.hashCode())
			{
				case -1338265852:
				{
					//line 4 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
					if (field.equals("onReady")) 
					{
						//line 4 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
						__temp_executeDef1 = false;
						//line 4 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
						this.onReady(((com.example.app.AppContext) (dynargs.__get(0)) ));
					}
					
					//line 4 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
					break;
				}
				
				
			}
			
			//line 4 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
			if (__temp_executeDef1) 
			{
				//line 4 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		//line 4 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Main.hx"
		return null;
	}
	
	
}


