// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
package com.example.app;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Main extends com.example.app.ZephyrApp
{
	public Main(haxe.lang.EmptyObject empty)
	{
		//line 6 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Main.hx"
		super(haxe.lang.EmptyObject.EMPTY);
	}
	
	
	public Main()
	{
		//line 1 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\libs\\android.jar@android\\app\\Activity.class (<init>)"
		super();
	}
	
	
	@Override public com.example.app.Page render()
	{
		//line 10 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Main.hx"
		com.example.app.Toolbar __temp_stmt3 = com.example.app.TagBuilder.toolbar(null);
		//line 11 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Main.hx"
		java.lang.Object __temp_stmt5 = null;
		//line 11 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Main.hx"
		{
			//line 11 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Main.hx"
			com.example.app.ListModel<java.lang.String> __temp_odecl1 = ((com.example.app.ListModel<java.lang.String>) (((com.example.app.ListModel) (com.example.app._AbstractListModel.AbstractListModel_Impl_.fromArray(((haxe.root.Array<java.lang.Object>) (((haxe.root.Array) (new haxe.root.Array<java.lang.String>(new java.lang.String[]{"Item 1", "Item 2", "Item 3", "Item 4"})) )) ))) )) );
			//line 13 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Main.hx"
			com.example.app.Main_render_13__Fun __temp_odecl2 = ( (( com.example.app.Main_render_13__Fun.__hx_current != null )) ? (com.example.app.Main_render_13__Fun.__hx_current) : (com.example.app.Main_render_13__Fun.__hx_current = ((com.example.app.Main_render_13__Fun) (new com.example.app.Main_render_13__Fun()) )) );
			//line 11 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Main.hx"
			__temp_stmt5 = new haxe.lang.DynamicObject(new java.lang.String[]{"dataSource", "renderItem"}, new java.lang.Object[]{__temp_odecl1, __temp_odecl2}, new java.lang.String[]{}, new double[]{});
		}
		
		//line 11 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Main.hx"
		com.example.app.Listview<java.lang.Object> __temp_stmt4 = com.example.app.TagBuilder.listview(((java.lang.Object) (__temp_stmt5) ));
		//line 9 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Main.hx"
		return com.example.app.TagBuilder.page(new haxe.root.Array<com.example.app.Tag>(new com.example.app.Tag[]{__temp_stmt3, ((com.example.app.Listview<java.lang.String>) (((com.example.app.Listview) (__temp_stmt4) )) )}));
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 6 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Main.hx"
		{
			//line 6 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Main.hx"
			boolean __temp_executeDef1 = true;
			//line 6 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Main.hx"
			switch (field.hashCode())
			{
				case -934592106:
				{
					//line 6 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Main.hx"
					if (field.equals("render")) 
					{
						//line 6 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Main.hx"
						__temp_executeDef1 = false;
						//line 6 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Main.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "render")) );
					}
					
					//line 6 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Main.hx"
					break;
				}
				
				
			}
			
			//line 6 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Main.hx"
			if (__temp_executeDef1) 
			{
				//line 6 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Main.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 6 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Main.hx"
				throw null;
			}
			
		}
		
	}
	
	
}


