// Generated by Haxe 3.4.2
package com.example.app;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class MainController extends com.example.app.Controller
{
	public MainController(haxe.lang.EmptyObject empty)
	{
		//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/MainController.hx"
		super(haxe.lang.EmptyObject.EMPTY);
	}
	
	
	public MainController()
	{
		//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
		super(haxe.lang.EmptyObject.EMPTY);
		//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
		com.example.app.MainController.__hx_ctor_com_example_app_MainController(this);
	}
	
	
	public static void __hx_ctor_com_example_app_MainController(com.example.app.MainController __hx_this)
	{
		//line 6 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Controller.hx"
		com.example.app.Controller.__hx_ctor_com_example_app_Controller(__hx_this);
	}
	
	
	@Override public void onEnter()
	{
		//line 9 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/MainController.hx"
		com.example.app.MainPage page = new com.example.app.MainPage();
		//line 10 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/MainController.hx"
		this.setPage(page);
	}
	
	
	@Override public void onLeave()
	{
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/MainController.hx"
		{
			//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/MainController.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/MainController.hx"
			switch (field.hashCode())
			{
				case -1343806440:
				{
					//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/MainController.hx"
					if (field.equals("onLeave")) 
					{
						//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/MainController.hx"
						__temp_executeDef1 = false;
						//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/MainController.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "onLeave")) );
					}
					
					//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/MainController.hx"
					break;
				}
				
				
				case -1349985223:
				{
					//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/MainController.hx"
					if (field.equals("onEnter")) 
					{
						//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/MainController.hx"
						__temp_executeDef1 = false;
						//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/MainController.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "onEnter")) );
					}
					
					//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/MainController.hx"
					break;
				}
				
				
			}
			
			//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/MainController.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/MainController.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/MainController.hx"
				throw null;
			}
			
		}
		
	}
	
	
}


