// Generated by Haxe 3.4.2
package com.example.app;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class MainPage_render_13__Fun extends haxe.lang.Function
{
	public MainPage_render_13__Fun()
	{
		//line 14 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/MainPage.hx"
		super(1, 0);
	}
	
	
	public static com.example.app.MainPage_render_13__Fun __hx_current;
	
	@Override public java.lang.Object __hx_invoke1_o(double __fn_float1, java.lang.Object __fn_dyn1)
	{
		//line 13 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/MainPage.hx"
		java.lang.String e = ( (( __fn_dyn1 == haxe.lang.Runtime.undefined )) ? (haxe.lang.Runtime.toString(__fn_float1)) : (haxe.lang.Runtime.toString(__fn_dyn1)) );
		//line 14 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/MainPage.hx"
		return com.example.app.TagBuilder.textview(new haxe.lang.DynamicObject(new java.lang.String[]{"text"}, new java.lang.Object[]{e}, new java.lang.String[]{}, new double[]{}));
	}
	
	
}


