// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
package com.example.app;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class OnClick extends haxe.lang.HxObject implements android.view.View.OnClickListener
{
	public OnClick(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public OnClick()
	{
		//line 14 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Toolbar.hx"
		com.example.app.OnClick.__hx_ctor_com_example_app_OnClick(this);
	}
	
	
	public static void __hx_ctor_com_example_app_OnClick(com.example.app.OnClick __hx_this)
	{
	}
	
	
	public void onClick(android.view.View view)
	{
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 14 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Toolbar.hx"
		{
			//line 14 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Toolbar.hx"
			boolean __temp_executeDef1 = true;
			//line 14 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Toolbar.hx"
			switch (field.hashCode())
			{
				case -1351902487:
				{
					//line 14 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Toolbar.hx"
					if (field.equals("onClick")) 
					{
						//line 14 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Toolbar.hx"
						__temp_executeDef1 = false;
						//line 14 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Toolbar.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "onClick")) );
					}
					
					//line 14 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Toolbar.hx"
					break;
				}
				
				
			}
			
			//line 14 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Toolbar.hx"
			if (__temp_executeDef1) 
			{
				//line 14 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Toolbar.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 14 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Toolbar.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		//line 14 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Toolbar.hx"
		{
			//line 14 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Toolbar.hx"
			boolean __temp_executeDef1 = true;
			//line 14 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Toolbar.hx"
			switch (field.hashCode())
			{
				case -1351902487:
				{
					//line 14 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Toolbar.hx"
					if (field.equals("onClick")) 
					{
						//line 14 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Toolbar.hx"
						__temp_executeDef1 = false;
						//line 14 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Toolbar.hx"
						this.onClick(((android.view.View) (dynargs.__get(0)) ));
					}
					
					//line 14 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Toolbar.hx"
					break;
				}
				
				
			}
			
			//line 14 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Toolbar.hx"
			if (__temp_executeDef1) 
			{
				//line 14 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Toolbar.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		//line 14 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\Toolbar.hx"
		return null;
	}
	
	
}


