// Generated by Haxe 3.4.2
package com.example.app;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Page extends haxe.lang.HxObject
{
	public Page(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Page()
	{
		//line 5 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
		com.example.app.Page.__hx_ctor_com_example_app_Page(this);
	}
	
	
	public static void __hx_ctor_com_example_app_Page(com.example.app.Page __hx_this)
	{
	}
	
	
	public com.example.app.Tag render()
	{
		//line 8 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
		throw haxe.lang.HaxeException.wrap("Not implemented");
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
		{
			//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
			switch (field.hashCode())
			{
				case -934592106:
				{
					//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
					if (field.equals("render")) 
					{
						//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
						__temp_executeDef1 = false;
						//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "render")) );
					}
					
					//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
					break;
				}
				
				
			}
			
			//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
		{
			//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
			switch (field.hashCode())
			{
				case -934592106:
				{
					//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
					if (field.equals("render")) 
					{
						//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
						__temp_executeDef1 = false;
						//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
						return this.render();
					}
					
					//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
					break;
				}
				
				
			}
			
			//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			else
			{
				//line 3 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Page.hx"
				throw null;
			}
			
		}
		
	}
	
	
}


