// Generated by Haxe 3.4.2
package com.example.app;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Toolbar extends com.example.app.Tag
{
	public Toolbar(haxe.lang.EmptyObject empty)
	{
		//line 28 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
		super(((haxe.lang.EmptyObject) (haxe.lang.EmptyObject.EMPTY) ));
	}
	
	
	public Toolbar(haxe.root.Array<com.example.app.Tag> tags)
	{
		//line 34 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
		super(((haxe.lang.EmptyObject) (haxe.lang.EmptyObject.EMPTY) ));
		//line 34 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
		com.example.app.Toolbar.__hx_ctor_com_example_app_Toolbar(this, tags);
	}
	
	
	public static void __hx_ctor_com_example_app_Toolbar(com.example.app.Toolbar __hx_this, haxe.root.Array<com.example.app.Tag> tags)
	{
		//line 34 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
		com.example.app.Tag.__hx_ctor_com_example_app_Tag(__hx_this, tags);
	}
	
	
	@Override public android.view.View render(android.content.Context context)
	{
		//line 42 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
		try 
		{
			//line 43 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			android.widget.LinearLayout layout = new android.widget.LinearLayout(context);
			//line 44 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			layout.setOrientation(((int) (android.widget.LinearLayout.HORIZONTAL) ));
			//line 45 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			layout.setWeightSum(((float) (1) ));
			//line 46 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			android.widget.LinearLayout.LayoutParams params = new android.widget.LinearLayout.LayoutParams(((int) (-1) ), ((int) (-2) ));
			//line 47 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			float scale = context.getResources().getDisplayMetrics().density;
			//line 47 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params.height = ((int) (java.lang.Math.round(( ( 50 * scale ) + 0.5 ))) );
			//line 48 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params.weight = ((float) (0) );
			//line 49 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			layout.setLayoutParams(((android.view.ViewGroup.LayoutParams) (params) ));
			//line 50 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			android.graphics.drawable.ColorDrawable color = new android.graphics.drawable.ColorDrawable(-12759108);
			//line 51 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			layout.setBackground(((android.graphics.drawable.Drawable) (color) ));
			//line 53 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			java.io.InputStream ims = context.getAssets().open(haxe.lang.Runtime.toString("bars.png"));
			//line 54 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			android.graphics.drawable.Drawable bars = android.graphics.drawable.Drawable.createFromStream(((java.io.InputStream) (ims) ), haxe.lang.Runtime.toString(null));
			//line 55 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			java.io.InputStream ims1 = context.getAssets().open(haxe.lang.Runtime.toString("map-marker.png"));
			//line 56 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			android.graphics.drawable.Drawable marker = android.graphics.drawable.Drawable.createFromStream(((java.io.InputStream) (ims1) ), haxe.lang.Runtime.toString(null));
			//line 57 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			java.io.InputStream ims2 = context.getAssets().open(haxe.lang.Runtime.toString("pencil.png"));
			//line 58 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			android.graphics.drawable.Drawable pencil = android.graphics.drawable.Drawable.createFromStream(((java.io.InputStream) (ims2) ), haxe.lang.Runtime.toString(null));
			//line 60 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			color = new android.graphics.drawable.ColorDrawable(0);
			//line 62 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			android.widget.ImageButton imageButton = new android.widget.ImageButton(context);
			//line 63 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params = new android.widget.LinearLayout.LayoutParams(((int) (-2) ), ((int) (-2) ));
			//line 64 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			float scale1 = context.getResources().getDisplayMetrics().density;
			//line 64 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params.width = ((int) (java.lang.Math.round(( ( 30 * scale1 ) + 0.5 ))) );
			//line 65 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			float scale2 = context.getResources().getDisplayMetrics().density;
			//line 65 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params.height = ((int) (java.lang.Math.round(( ( 30 * scale2 ) + 0.5 ))) );
			//line 66 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params.gravity = 17;
			//line 67 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params.weight = ((float) (0) );
			//line 68 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			float scale3 = context.getResources().getDisplayMetrics().density;
			//line 68 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params.leftMargin = ((int) (java.lang.Math.round(( ( 5 * scale3 ) + 0.5 ))) );
			//line 69 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			imageButton.setLayoutParams(((android.view.ViewGroup.LayoutParams) (params) ));
			//line 70 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			imageButton.setBackground(((android.graphics.drawable.Drawable) (color) ));
			//line 71 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			imageButton.setImageDrawable(((android.graphics.drawable.Drawable) (bars) ));
			//line 72 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			imageButton.setOnClickListener(((android.view.View.OnClickListener) (new com.example.app.OnClick()) ));
			//line 73 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			layout.addView(((android.view.View) (imageButton) ));
			//line 75 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			android.widget.TextView textView = new android.widget.TextView(context);
			//line 76 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			textView.setGravity(((int) (17) ));
			//line 77 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			textView.setText(((java.lang.CharSequence) ("Header bar") ));
			//line 78 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			textView.setTextColor(((int) (-1) ));
			//line 79 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params = new android.widget.LinearLayout.LayoutParams(((int) (-2) ), ((int) (-2) ));
			//line 80 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params.gravity = 17;
			//line 81 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params.weight = ((float) (1) );
			//line 82 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			textView.setLayoutParams(((android.view.ViewGroup.LayoutParams) (params) ));
			//line 83 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			layout.addView(((android.view.View) (textView) ));
			//line 85 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			imageButton = new android.widget.ImageButton(context);
			//line 86 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params = new android.widget.LinearLayout.LayoutParams(((int) (-2) ), ((int) (-2) ));
			//line 87 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			float scale4 = context.getResources().getDisplayMetrics().density;
			//line 87 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params.width = ((int) (java.lang.Math.round(( ( 30 * scale4 ) + 0.5 ))) );
			//line 88 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			float scale5 = context.getResources().getDisplayMetrics().density;
			//line 88 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params.height = ((int) (java.lang.Math.round(( ( 30 * scale5 ) + 0.5 ))) );
			//line 89 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params.gravity = 17;
			//line 90 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params.weight = ((float) (0) );
			//line 91 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			float scale6 = context.getResources().getDisplayMetrics().density;
			//line 91 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params.leftMargin = ((int) (java.lang.Math.round(( ( 5 * scale6 ) + 0.5 ))) );
			//line 92 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			imageButton.setLayoutParams(((android.view.ViewGroup.LayoutParams) (params) ));
			//line 93 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			imageButton.setBackground(((android.graphics.drawable.Drawable) (color) ));
			//line 94 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			imageButton.setImageDrawable(((android.graphics.drawable.Drawable) (marker) ));
			//line 95 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			layout.addView(((android.view.View) (imageButton) ));
			//line 97 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			imageButton = new android.widget.ImageButton(context);
			//line 98 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params = new android.widget.LinearLayout.LayoutParams(((int) (-2) ), ((int) (-2) ));
			//line 99 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			float scale7 = context.getResources().getDisplayMetrics().density;
			//line 99 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params.width = ((int) (java.lang.Math.round(( ( 30 * scale7 ) + 0.5 ))) );
			//line 100 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			float scale8 = context.getResources().getDisplayMetrics().density;
			//line 100 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params.height = ((int) (java.lang.Math.round(( ( 30 * scale8 ) + 0.5 ))) );
			//line 101 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params.gravity = 17;
			//line 102 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params.weight = ((float) (0) );
			//line 103 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			float scale9 = context.getResources().getDisplayMetrics().density;
			//line 103 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params.rightMargin = ((int) (java.lang.Math.round(( ( 5 * scale9 ) + 0.5 ))) );
			//line 104 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			float scale10 = context.getResources().getDisplayMetrics().density;
			//line 104 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			params.leftMargin = ((int) (java.lang.Math.round(( ( 5 * scale10 ) + 0.5 ))) );
			//line 105 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			imageButton.setLayoutParams(((android.view.ViewGroup.LayoutParams) (params) ));
			//line 106 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			imageButton.setBackground(((android.graphics.drawable.Drawable) (color) ));
			//line 107 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			imageButton.setImageDrawable(((android.graphics.drawable.Drawable) (pencil) ));
			//line 108 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			layout.addView(((android.view.View) (imageButton) ));
			//line 110 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			return layout;
		}
		catch (java.lang.Throwable typedException)
		{
			//line 42 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			throw haxe.lang.HaxeException.wrap(typedException);
		}
		
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 28 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
		{
			//line 28 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			boolean __temp_executeDef1 = true;
			//line 28 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			switch (field.hashCode())
			{
				case -934592106:
				{
					//line 28 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
					if (field.equals("render")) 
					{
						//line 28 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
						__temp_executeDef1 = false;
						//line 28 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "render")) );
					}
					
					//line 28 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
					break;
				}
				
				
			}
			
			//line 28 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
			if (__temp_executeDef1) 
			{
				//line 28 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 28 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/Toolbar.hx"
				throw null;
			}
			
		}
		
	}
	
	
}


