// Generated by Haxe 3.4.2
package com.example.app;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class VBox extends com.example.app.Tag
{
	public VBox(haxe.lang.EmptyObject empty)
	{
		//line 9 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
		super(((haxe.lang.EmptyObject) (haxe.lang.EmptyObject.EMPTY) ));
	}
	
	
	public VBox(haxe.root.Array<com.example.app.Tag> tags)
	{
		//line 16 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
		super(((haxe.lang.EmptyObject) (haxe.lang.EmptyObject.EMPTY) ));
		//line 16 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
		com.example.app.VBox.__hx_ctor_com_example_app_VBox(this, tags);
	}
	
	
	public static void __hx_ctor_com_example_app_VBox(com.example.app.VBox __hx_this, haxe.root.Array<com.example.app.Tag> tags)
	{
		//line 16 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
		com.example.app.Tag.__hx_ctor_com_example_app_Tag(__hx_this, tags);
	}
	
	
	@Override public android.view.View render(android.content.Context context)
	{
		//line 25 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
		android.widget.LinearLayout layout = new android.widget.LinearLayout(context);
		//line 26 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
		layout.setOrientation(((int) (android.widget.LinearLayout.VERTICAL) ));
		//line 27 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
		layout.setWeightSum(((float) (1) ));
		//line 28 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
		android.widget.LinearLayout.LayoutParams params = new android.widget.LinearLayout.LayoutParams(((int) (-1) ), ((int) (-1) ));
		//line 30 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
		haxe.root.Array<android.view.View> childs = this.renderChilds(context);
		//line 31 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
		{
			//line 31 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
			int _g = 0;
			//line 31 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
			while (( _g < childs.length ))
			{
				//line 31 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
				android.view.View i = childs.__get(_g);
				//line 31 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
				 ++ _g;
				//line 32 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
				layout.addView(((android.view.View) (i) ));
			}
			
		}
		
		//line 35 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
		layout.setLayoutParams(((android.view.ViewGroup.LayoutParams) (params) ));
		//line 37 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
		return layout;
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 9 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
		{
			//line 9 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
			boolean __temp_executeDef1 = true;
			//line 9 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
			switch (field.hashCode())
			{
				case -934592106:
				{
					//line 9 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
					if (field.equals("render")) 
					{
						//line 9 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
						__temp_executeDef1 = false;
						//line 9 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "render")) );
					}
					
					//line 9 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
					break;
				}
				
				
			}
			
			//line 9 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
			if (__temp_executeDef1) 
			{
				//line 9 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 9 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/VBox.hx"
				throw null;
			}
			
		}
		
	}
	
	
}


