// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
package com.example.app._AbstractListModel;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public final class AbstractListModel_Impl_
{
	public static <T> com.example.app.ListModel<T> fromArray(haxe.root.Array<T> array)
	{
		//line 11 "d:\\Workspace\\Haxe\\tests\\TestAndroid\\AppWithGradleTemplate\\source\\com\\example\\app\\AbstractListModel.hx"
		return new com.example.app.ListModel<T>(((haxe.root.Array<T>) (array) ));
	}
	
	
}


