// Generated by Haxe 3.4.2
package com.example.app._AbstractListModel;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public final class AbstractListModel_Impl_
{
	public static <T> com.example.app.ListModel<T> fromArray(haxe.root.Array<T> array)
	{
		//line 11 "/home/grabli66/Workspace/ZephyrNative/source/com/example/app/AbstractListModel.hx"
		return new com.example.app.ListModel<T>(((haxe.root.Array<T>) (array) ));
	}
	
	
}


